### ISSUE TITLE
Restore MacOS support

### ISSUE THREAD

**Issue by chrisbrickhouse** [Forced-Alignment-and-Vowel-Extraction/fave-asr#1]
In our chain of dependencies  `openai-whisper` depends `pyannote-audio` depends `onnxruntime-gpu>=1.16.0`

`onnxruntime-gpu` does not support MacOS ([issue](https://github.com/microsoft/onnxruntime/issues/12252)). This dependency appears to have been added to `pyannote-audio` in the 3.0.1 release ([issue](https://github.com/pyannote/pyannote-audio/issues/1505)).

For the moment we will need to drop plans for MacOS support. The short-term resolution is to pin `pyannote-audio==3.0.0` but this is not ideal given the potential conflicts as other dependencies bump versions. The long-term solution would be upstream changes, but we have no control over what upstream does. 

For the moment I will chalk this up as code debt given that I have no need to run this on Mac, but it will be a hurdle when we move towards an initial release.

**Comment by JoFrhwld** [comment]
fyi, it looks like pyannote has an open PR about this: https://github.com/pyannote/pyannote-audio/pull/1540

**Comment by JoFrhwld** [comment]
And, it's been released! https://github.com/pyannote/pyannote-audio/releases/tag/3.1.0
